set_property IOSTANDARD LVCMOS33 [get_ports {sw[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn[0]}]
set_property DRIVE 12 [get_ports {led[0]}]
set_property SLEW SLOW [get_ports {led[0]}]
set_property PACKAGE_PIN U12 [get_ports {btn[0]}]
set_property PACKAGE_PIN V12 [get_ports {btn[1]}]
set_property PACKAGE_PIN U7 [get_ports {btn[2]}]
set_property PACKAGE_PIN Y6 [get_ports {btn[3]}]
set_property PACKAGE_PIN Y9 [get_ports {led[0]}]
set_property PACKAGE_PIN Y8 [get_ports {led[1]}]
set_property PACKAGE_PIN V7 [get_ports {led[2]}]
set_property PACKAGE_PIN W7 [get_ports {led[3]}]
set_property PACKAGE_PIN V10 [get_ports {led[4]}]
set_property PACKAGE_PIN W12 [get_ports {led[5]}]
set_property PACKAGE_PIN W11 [get_ports {led[6]}]
set_property PACKAGE_PIN V8 [get_ports {led[7]}]

set_property PACKAGE_PIN J20 [get_ports {sseg_an[3]}]
set_property PACKAGE_PIN J18 [get_ports {sseg_an[2]}]
set_property PACKAGE_PIN H20 [get_ports {sseg_an[1]}]
set_property PACKAGE_PIN K19 [get_ports {sseg_an[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg_an[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg_an[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg_an[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg_an[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports sseg_ca]
set_property IOSTANDARD LVCMOS33 [get_ports sseg_cb]
set_property IOSTANDARD LVCMOS33 [get_ports sseg_cc]
set_property IOSTANDARD LVCMOS33 [get_ports sseg_cd]
set_property IOSTANDARD LVCMOS33 [get_ports sseg_ce]
set_property IOSTANDARD LVCMOS33 [get_ports sseg_cf]
set_property IOSTANDARD LVCMOS33 [get_ports sseg_cg]
set_property IOSTANDARD LVCMOS33 [get_ports sseg_dp]
set_property IOSTANDARD LVCMOS33 [get_ports sysclk_125mhz]
set_property PACKAGE_PIN K20 [get_ports sseg_dp]
set_property PACKAGE_PIN L19 [get_ports sseg_cg]
set_property PACKAGE_PIN H18 [get_ports sseg_cf]
set_property PACKAGE_PIN M20 [get_ports sseg_ce]
set_property PACKAGE_PIN K21 [get_ports sseg_cd]
set_property PACKAGE_PIN K18 [get_ports sseg_cc]
set_property PACKAGE_PIN H17 [get_ports sseg_cb]
set_property PACKAGE_PIN H19 [get_ports sseg_ca]


set_property PACKAGE_PIN L18 [get_ports sysclk_125mhz]
set_property PACKAGE_PIN V9 [get_ports {sw[7]}]
set_property PACKAGE_PIN W10 [get_ports {sw[6]}]
set_property PACKAGE_PIN U9 [get_ports {sw[5]}]
set_property PACKAGE_PIN W8 [get_ports {sw[4]}]
set_property PACKAGE_PIN V4 [get_ports {sw[3]}]
set_property PACKAGE_PIN T4 [get_ports {sw[2]}]
set_property PACKAGE_PIN U5 [get_ports {sw[1]}]
set_property PACKAGE_PIN T6 [get_ports {sw[0]}]


set_property PACKAGE_PIN R15 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]


